### ISSUE TITLE
Library is compiled for preview JUnit 5.11.0-M2

### ISSUE THREAD

**Issue by michaldo** [hosuaby/inject-resources#24]
Current JUnit version is 5.10.3 and code should be compiled to this version

`inject-resources` fails with

> java.lang.NoSuchMethodError: 'java.lang.reflect.Field org.junit.platform.commons.util.ReflectionUtils.makeAccessible(java.lang.reflect.Field)'

**Comment by hosuaby** [comment]
Library is compiled to work with multiple versions of JUnit, and 5.10.3 is one of them. This exception with reflexion may be due to version of Java. Which version are you using?

**Comment by michaldo** [comment]
> Library is compiled to work with multiple versions of JUnit, and 5.10.3 is one of them.

I would rather say "The library is compiled _in hope_ to work with multiple versions of JUnit..."

It works with 5.11 with methods:

https://github.com/junit-team/junit5/blob/r5.11.0-M2/junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java#L1905

It does not work with 5.10 with methods:

https://github.com/junit-team/junit5/blob/r5.10.3/junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java#L1769

BTW, in order to work with multiple versions of JUnit, code like "makeAccessible" should be self-implemented

**Comment by hosuaby** [comment]
Here the example using inject-resources 0.3.4 with JUnit 5.10.3: https://github.com/hosuaby/biskot-impl
It's working.

Can you provide example of failing test? Also, know your Java version would be helpful.

**Comment by michaldo** [comment]
The following code does not work for 5.10.3 and 0.3.4

@TestWithResources
class MyTest {

    @GivenTextResource("/file.txt")
    String file;

    @Test
    void test() {
        System.out.println(file);
    }


But the following works:

@Test
void ***@***.***("/file.txt") String file) {

System.out.println(file);

Java 21


wt., 30 lip 2024 o 10:01 Alexei KLENIN ***@***.***>
napisał(a):

**Comment by michaldo** [comment]
The following code does not work for 5.10.3 and 0.3.4
```
@TestWithResources
class MyTest {

    @GivenTextResource("/file.txt")
    String file;

    @Test
    void test() {
        System.out.println(file);
    }
```
But the following, surprisingly works:
```
@Test
void test(@GivenTextResource("/file.txt") String file) {
    System.out.println(file); 
```
Java 21

**Comment by hosuaby** [comment]
I confirm this bug. looking for right solution.

**Comment by hosuaby** [comment]
Fixed in 0.3.5
